name = "probabilisticBisection"
uuid = "b5070372-cb8e-4794-a866-e260982f6ebc"
authors = ["Christopher Marcotte <christopher.marcotte@durham.ac.uk>"]
version = "0.1.0"

[deps]

[weakdeps]

[extensions]

[compat]
Test = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
